let currentPage = "home", currentMonth = new Date().getMonth()+1, currentYear = new Date().getFullYear(), transactionType = "expense", chart1, chart2;
document.querySelectorAll(".nav-item").forEach(item => item.addEventListener("click", () => switchPage(item.dataset.page)));
document.getElementById("fabAddBtn")?.addEventListener("click", () => switchPage("add"));
document.getElementById("viewAllBtn")?.addEventListener("click", () => switchPage("transactions"));
function switchPage(page) { currentPage = page; document.querySelectorAll(".page").forEach(p => p.classList.remove("active")); document.getElementById(`page-${page}`).classList.add("active"); document.querySelectorAll(".nav-item").forEach(item => { if(item.dataset.page === page) item.classList.add("active"); else item.classList.remove("active"); }); if(page === "home") loadHome(); if(page === "transactions") loadTransactions(); if(page === "reports") loadReports(); if(page === "budget") loadBudgetPage(); }
document.getElementById("typeExpenseBtn")?.addEventListener("click", () => transactionType = "expense");
document.getElementById("typeIncomeBtn")?.addEventListener("click", () => transactionType = "income");
document.getElementById("saveTransactionBtn")?.addEventListener("click", async () => {
    let payload = { expense_date: document.getElementById("expenseDate").value, type: transactionType, amount: parseFloat(document.getElementById("amount").value), category: document.getElementById("category").value, description: document.getElementById("description").value || "-", currency: document.getElementById("currency").value };
    if(!payload.expense_date || isNaN(payload.amount) || payload.amount <= 0) return Swal.fire("กรุณากรอกข้อมูล","","warning");
    showLoading(); await addExpense(payload); Swal.fire("บันทึกสำเร็จ!","","success"); document.getElementById("amount").value = ""; switchPage("home"); loadHome(); hideLoading();
});
async function loadHome() { showLoading(); let [expenses, summary, cats] = await Promise.all([getExpenses(currentMonth,currentYear), getMonthlySummary(currentMonth,currentYear), getCategorySummary(currentMonth,currentYear)]); let recent = expenses.slice(0,5); document.getElementById("recentTransactions").innerHTML = recent.map(t => `<div class="transaction-item"><div>${t.category}</div><div class="${t.type==="income"?"amount-income":"amount-expense"}">${t.type==="income"?"+":"-"} ${t.amount} ${t.currency}</div><div class="text-xs">${t.expense_date}</div></div>`).join("") || "<div>ไม่มีรายการ</div>"; document.getElementById("totalIncome").innerHTML = (summary.income?.THB||0).toFixed(2); document.getElementById("totalExpense").innerHTML = (summary.expense?.THB||0).toFixed(2); document.getElementById("netBalance").innerHTML = (summary.net?.THB||0).toFixed(2); if(chart1) chart1.destroy(); chart1 = new Chart(document.getElementById("categoryChart"), { type:"doughnut", data:{ labels:cats.labels||[], datasets:[{ data:cats.data||[], backgroundColor:["#818cf8","#f97316","#34d399","#f87171","#a855f7"] }] } }); hideLoading(); }
async function loadTransactions() { showLoading(); let expenses = await getExpenses(currentMonth,currentYear); document.getElementById("allTransactionsList").innerHTML = expenses.map(t => `<div class="transaction-item"><div>${t.category} - ${t.expense_date}</div><div>${t.type==="income"?"+":"-"} ${t.amount} ${t.currency}</div><button onclick="deleteTrans(${t.id})">ลบ</button></div>`).join("") || "<div>ไม่มีรายการ</div>"; hideLoading(); }
window.deleteTrans = async (id) => { if(await Swal.fire({ title:"ลบ?", showCancelButton:true }).then(r=>r.isConfirmed)) { showLoading(); await deleteExpense(id); loadTransactions(); loadHome(); hideLoading(); Swal.fire("ลบแล้ว"); } };
async function loadReports() { showLoading(); let summary = await getMonthlySummary(currentMonth,currentYear); if(chart2) chart2.destroy(); chart2 = new Chart(document.getElementById("trendChart"), { type:"bar", data:{ labels:["รายรับ","รายจ่าย","คงเหลือ"], datasets:[{ label:"บาท", data:[summary.income?.THB||0, summary.expense?.THB||0, summary.net?.THB||0], backgroundColor:["#34d399","#f87171","#818cf8"] }] } }); let cats = await getCategorySummary(currentMonth,currentYear); let top = cats.labels?.map((l,i)=>({l,v:cats.data[i]})).sort((a,b)=>b.v-a.v).slice(0,5)||[]; document.getElementById("topCategories").innerHTML = top.map(t=>`<div>${t.l} ${t.v.toFixed(2)}</div>`).join(""); hideLoading(); }
async function loadBudgetPage() { let budgets = await getBudgets(currentMonth,currentYear); document.getElementById("budgetThb").value = budgets.THB||""; document.getElementById("budgetUsd").value = budgets.USD||""; document.getElementById("budgetEur").value = budgets.EUR||""; let summary = await getMonthlySummary(currentMonth,currentYear); let alertDiv = document.getElementById("budgetAlert"); if(budgets.THB >0 && summary.expense?.THB > budgets.THB) alertDiv.innerText = `เกินงบ! ใช้ ${summary.expense.THB} / ${budgets.THB}`; else alertDiv.innerText = ""; }
document.getElementById("saveBudgetBtn")?.addEventListener("click", async () => { let budgets = { THB: parseFloat(document.getElementById("budgetThb").value)||0, USD: parseFloat(document.getElementById("budgetUsd").value)||0, EUR: parseFloat(document.getElementById("budgetEur").value)||0 }; showLoading(); await setBudgets(currentMonth,currentYear,budgets); Swal.fire("บันทึกงบแล้ว"); hideLoading(); loadBudgetPage(); });
function initSelects() { for(let i=1;i<=12;i++) document.getElementById("monthSelect")?.insertAdjacentHTML("beforeend", `<option value="${i}">${i}</option>`); document.getElementById("monthSelect").value = currentMonth; document.getElementById("monthSelect")?.addEventListener("change", (e)=>{ currentMonth=parseInt(e.target.value); loadTransactions(); }); for(let y=2023;y<=2028;y++) document.getElementById("yearSelect")?.insertAdjacentHTML("beforeend", `<option value="${y}">${y}</option>`); document.getElementById("yearSelect").value = currentYear; document.getElementById("yearSelect")?.addEventListener("change", (e)=>{ currentYear=parseInt(e.target.value); loadTransactions(); }); document.getElementById("expenseDate").valueAsDate = new Date(); }
initSelects(); loadHome();
